import os
import json
import requests
from datetime import datetime, timezone

USERNAME = "BananaOfficial"
ORG = "RequestTimeout"
API = "https://api.github.com"
TOKEN = os.getenv("GITHUB_TOKEN")

headers = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"Bearer {TOKEN}",
    "X-GitHub-Api-Version": "2026-03-10"
}

def get(url):
    r = requests.get(url, headers=headers)
    r.raise_for_status()
    return r.json()

user = get(f"{API}/users/{USERNAME}")

profile = user.get("bio") or ""

repos = []
page = 1

while True:
    data = get(f"{API}/users/{USERNAME}/repos?per_page=100&page={page}")

    if not data:
        break

    repos.extend(data)
    page += 1

public_repos = len(repos)
total_stars = sum(repo["stargazers_count"] for repo in repos)

now = datetime.now(timezone.utc)
total_contributions = 0

for year in range(2026, 2017, -1):
    start = f"{year}-01-01T00:00:00Z"
    end = f"{year}-12-31T23:59:59Z"

    query = """
    query($login: String!, $from: DateTime!, $to: DateTime!) {
      user(login: $login) {
        contributionsCollection(from: $from, to: $to) {
          contributionCalendar {
            totalContributions
          }
        }
      }
    }
    """

    r = requests.post(
        f"{API}/graphql",
        headers=headers,
        json={
            "query": query,
            "variables": {
                "login": USERNAME,
                "from": start,
                "to": end
            }
        }
    )

    r.raise_for_status()
    data = r.json()

    total_contributions += (
        data["data"]["user"]["contributionsCollection"]
        ["contributionCalendar"]["totalContributions"]
    )

views_file = "views.json"

if os.path.exists(views_file):
    with open(views_file, "r") as f:
        history = json.load(f)
else:
    history = {}

today = now.strftime("%Y-%m-%d")
today_views = 0

org_repos = []
page = 1

while True:
    data = get(f"{API}/orgs/{ORG}/repos?per_page=100&page={page}")

    if not data:
        break

    org_repos.extend(data)
    page += 1

for repo in org_repos:
    try:
        data = get(
            f"{API}/repos/{ORG}/{repo['name']}/traffic/views"
        )
        today_views += data.get("count", 0)
    except requests.HTTPError:
        pass

history[today] = today_views

total_views = sum(history.values())

svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="700" height="250" viewBox="0 0 700 250">
<rect width="700" height="250" rx="20" fill="#0d1117"/>
<text x="35" y="45" fill="#ffffff" font-size="25" font-family="Arial" font-weight="bold">BananaOfficial</text>
<text x="35" y="75" fill="#8b949e" font-size="16" font-family="Arial">{profile}</text>

<text x="35" y="125" fill="#ffffff" font-size="16" font-family="Arial">Stars</text>
<text x="35" y="150" fill="#58a6ff" font-size="24" font-family="Arial">{total_stars}</text>

<text x="190" y="125" fill="#ffffff" font-size="16" font-family="Arial">Public Repos</text>
<text x="190" y="150" fill="#58a6ff" font-size="24" font-family="Arial">{public_repos}</text>

<text x="390" y="125" fill="#ffffff" font-size="16" font-family="Arial">Views</text>
<text x="390" y="150" fill="#58a6ff" font-size="24" font-family="Arial">{total_views}</text>

<text x="520" y="125" fill="#ffffff" font-size="16" font-family="Arial">Contributions</text>
<text x="520" y="150" fill="#58a6ff" font-size="24" font-family="Arial">{total_contributions}</text>

<text x="35" y="215" fill="#8b949e" font-size="13" font-family="Arial">Generated by RequestTimeout</text>
</svg>'''
